/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#13131b',
        'surface-dim': '#13131b',
        'surface-bright': '#393841',
        'surface-container-lowest': '#0d0d15',
        'surface-container-low': '#1b1b23',
        'surface-container': '#1f1f27',
        'surface-container-high': '#292932',
        'surface-container-highest': '#34343d',
        'on-surface': '#e4e1ed',
        'on-surface-variant': '#c7c4d7',
        'inverse-surface': '#e4e1ed',
        'inverse-on-surface': '#303038',
        outline: '#908fa0',
        'outline-variant': '#464554',
        'surface-tint': '#c0c1ff',
        primary: '#c0c1ff',
        'on-primary': '#1000a9',
        'primary-container': '#8083ff',
        'on-primary-container': '#0d0096',
        'inverse-primary': '#494bd6',
        secondary: '#ddb7ff',
        'on-secondary': '#490080',
        'secondary-container': '#6f00be',
        'on-secondary-container': '#d6a9ff',
        tertiary: '#ffb783',
        'on-tertiary': '#4f2500',
        'tertiary-container': '#d97721',
        'on-tertiary-container': '#452000',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#e1e0ff',
        'primary-fixed-dim': '#c0c1ff',
        'on-primary-fixed': '#07006c',
        'on-primary-fixed-variant': '#2f2ebe',
        'secondary-fixed': '#f0dbff',
        'secondary-fixed-dim': '#ddb7ff',
        'on-secondary-fixed': '#2c0051',
        'on-secondary-fixed-variant': '#6900b3',
        'tertiary-fixed': '#ffdcc5',
        'tertiary-fixed-dim': '#ffb783',
        'on-tertiary-fixed': '#301400',
        'on-tertiary-fixed-variant': '#703700',
        background: '#13131b',
        'on-background': '#e4e1ed',
        'surface-variant': '#34343d'
      },
      fontFamily: {
        sans: ['Geist', 'sans-serif'],
      },
      spacing: {
        'unit': '8px',
        'gutter': '24px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px'
      }
    },
  },
  plugins: [],
}
